name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Test path
      working-directory: pintos/src/filesys/
      run: ls
      
    - name: Build and run tests
      run: cd pintos/src/filesys/ && make #&& make check
      
